test:
	forest ./binary_search/config.xml
	forest ./break_cond_loop/config.xml
	forest ./continue_cond_loop/config.xml
	forest ./cross_iteration_deps/config.xml
	forest ./cross_iteration_deps_fake/config.xml
	forest ./dead_loop/config.xml
	forest ./exit_call_loop/config.xml
	forest ./func_call_loop/config.xml
	forest ./graph_traversal_update/config.xml
	forest ./indirect_exit_call_loop/config.xml
	forest ./indirect_longjmp_call_loop/config.xml
	forest ./infinite_loop/config.xml
	forest ./io_call_loop/config.xml
	forest ./linear_search/config.xml
	forest ./list_traversal_update/config.xml
	forest ./longjmp_call_loop/config.xml
	forest ./Makefile/config.xml
	forest ./map_mandelbrot/config.xml
	forest ./map_reduce_dot_product/config.xml
	forest ./map_saxpy/config.xml
	forest ./map_simple/config.xml
	forest ./matrix_product/config.xml
	forest ./reduce_add/config.xml
	forest ./reduce_concat/config.xml
	forest ./reduce_histogram/config.xml
	forest ./reduce_tree_add/config.xml
	forest ./regular_inner_loop1/config.xml
	forest ./regular_inner_loop2/config.xml
	forest ./regular_loop/config.xml
	forest ./return_stmt_inner_loop/config.xml
	forest ./return_stmt_loop/config.xml
	forest ./return_stmt_with_val_loop/config.xml
	forest ./scan_add/config.xml
	forest ./special_calls_loop/config.xml
	forest ./stencil_simple/config.xml


