test:
	@forest ./math/config.xml                         # Simple math operations with integers
	@forest ./simple/config.xml                       # simple operations with a variable
	@forest ./uniform_test/config.xml                 # nested ifs
	@forest ./function/config.xml                     # function call
	@forest ./concrete_return/config.xml              # Llamada a funciones no anotadas
