test:
	@forest ./test/for_infinite_loop_1/config.xml          # Simple infinite loop
	@forest ./test/for_infinite_loop_2/config.xml          # Simple infinite loop
	@forest ./test/for_infinite_loop_3/config.xml          # Simple infinite loop
	@forest ./test/terminator_01/config.xml                # Terminator loop
	@forest ./test/terminator_02/config.xml                # Terminator loop 2
	@forest ./test/terminator_03/config.xml                # Terminator loop 3
	@forest ./test/while_infinite_loop_1/config.xml        # While infinite loop
	@forest ./test/while_infinite_loop_3/config.xml        # While infinite loop
