test:
	@forest ./sign_ext/config.xml               # Sign Extension
	@forest ./sign_extr/config.xml              # Sign Extraction
	@forest ./unsigned_uneq/config.xml          # Unsigned wrapped unequality
	@forest ./wrap_neg/config.xml               # Negative wrap
	@forest ./wrap_pos/config.xml               # Positive wrap
	@forest ./wrap_pos_2/config.xml             # Positive wrap
	@forest ./wrap_pos_uneq/config.xml          # Positive wrap
	@forest ./wrap_pos_uneq_unsigned/config.xml # Positive wrap
	@forest ./wrap_pos_unsigned/config.xml      # Positive wrapped
