all:
	witness_check example_0/witness.graphml example_0/example0_false-unreach-label.c
	witness_check example_1/witness.graphml example_1/example_1.c
	witness_check example_2/witness.graphml example_2/example_2.c
	witness_check example_3/witness.graphml example_3/example_3.c
	witness_check example_4/witness.graphml example_4/example_4.c
